# This file was generated by GoReleaser. DO NOT EDIT.
cask "codeflow@beta" do
  version "0.1.0-alpha.436"

  on_macos do
    on_intel do
      sha256 "560edec83c3ff2aaf7d6fb118e0e8d41079823f615acb403e607a9bf852f2751"
      url "https://pkg.productmind.ai/beta/v#{version}/codeflow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "99922581f774ac58b04c3b9e6ab6556766c3bcf86e79be2f6592e8e6f5455835"
      url "https://pkg.productmind.ai/beta/v#{version}/codeflow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "29935075ddf502cd7c07145c69c8ed59909c11f17f03efd2826a6b3c771165ea"
      url "https://pkg.productmind.ai/beta/v#{version}/codeflow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6fba5fefc8d8ed8efdfd9d0090544a565ee13a67c88b9a96f7aa770ec369e16c"
      url "https://pkg.productmind.ai/beta/v#{version}/codeflow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "codeflow@beta"
  desc "Parallel AI coding agents and autonomous coding sessions"
  homepage "https://productmind.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codeflow"
  binary "cf-shell"
  binary "cf-attach"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/codeflow"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cf-shell"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cf-attach"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `codeflow init` for first-run setup, then `codeflow doctor` to verify
    your environment.

    Docker is required and is not installed by this cask.

    Public builds ship without a bundled TLS certificate for local previews.
    Set CODEFLOW_PREVIEW_TLS_CERT and CODEFLOW_PREVIEW_TLS_KEY to serve local
    previews over HTTPS; otherwise they are served over plain HTTP.
  EOS
end
