# This file was generated by GoReleaser. DO NOT EDIT.
cask "codeflow" do
  version "0.0.1-196"

  on_macos do
    on_intel do
      sha256 "729e12aada36e7ec595d26622dc7ab973c488082576ffb02842dca8251ab415f"
      url "https://pkg.productmind.ai/stable/v#{version}/codeflow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4ed5d3aec846a2082412b04f393cd06b5e9fe7d8350ab592b5e77f63f9ca4fb4"
      url "https://pkg.productmind.ai/stable/v#{version}/codeflow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "263ebe2fd7483b8ffa37d196c0863cd4f496056f0dd221a37aab834bb7545af0"
      url "https://pkg.productmind.ai/stable/v#{version}/codeflow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0702d271d24fbcf989574a7b39dac0e92a3fd139a8afc2edfecee6cbe113bb13"
      url "https://pkg.productmind.ai/stable/v#{version}/codeflow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "codeflow"
  desc "Parallel AI coding agents and autonomous coding sessions"
  homepage "https://productmind.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codeflow"
  binary "cf-shell"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/codeflow"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cf-shell"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `codeflow init` for first-run setup, then `codeflow doctor` to verify
    your environment.

    Docker is required and is not installed by this cask.

    Public builds ship without a bundled TLS certificate for local previews.
    Set CODEFLOW_PREVIEW_TLS_CERT and CODEFLOW_PREVIEW_TLS_KEY to serve local
    previews over HTTPS; otherwise they are served over plain HTTP.
  EOS
end
