# This file was generated by GoReleaser. DO NOT EDIT.
cask "codeflow" do
  version "0.0.1-463"

  on_macos do
    on_intel do
      sha256 "cb9326d1ab3c14d3b5ad93196ee92b03c478ea2fbb6ba93affd0f309d879307e"
      url "https://pkg.productmind.ai/stable/v#{version}/codeflow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "85d6e9934401a7872fc8debc1886e44c8356552aaf0d5c15c5a8176836381fa3"
      url "https://pkg.productmind.ai/stable/v#{version}/codeflow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "abcc7bb60e5046041ec21f59e5dd66eebb513773546cb08150c18bde68470f03"
      url "https://pkg.productmind.ai/stable/v#{version}/codeflow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a11456706eeab04a7f812c56a0d3bcf86501ffe91b560c2d0ecb27e76b730c46"
      url "https://pkg.productmind.ai/stable/v#{version}/codeflow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "codeflow"
  desc "Parallel AI coding agents and autonomous coding sessions"
  homepage "https://productmind.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codeflow"
  binary "cf-shell"
  binary "cf-attach"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/codeflow"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cf-shell"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cf-attach"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `codeflow init` for first-run setup, then `codeflow doctor` to verify
    your environment.

    Docker is required and is not installed by this cask.

    Public builds ship without a bundled TLS certificate for local previews.
    Set CODEFLOW_PREVIEW_TLS_CERT and CODEFLOW_PREVIEW_TLS_KEY to serve local
    previews over HTTPS; otherwise they are served over plain HTTP.
  EOS
end
