# This file was generated by GoReleaser. DO NOT EDIT.
cask "codeflow" do
  version "0.0.1-545"

  on_macos do
    on_intel do
      sha256 "d43c616a0ed7abe024a356400ee6163526a2270d760edb8b5a8cea3456d38fcd"
      url "https://pkg.productmind.ai/stable/v#{version}/codeflow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1e3c671e195f0226f8caee2261498b24be7d9e6e9273c2914a1b0f52eacb4ac0"
      url "https://pkg.productmind.ai/stable/v#{version}/codeflow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d19128ebb2b9939091859606b4d69676c558b2be4cfad0441f45cf379c92e343"
      url "https://pkg.productmind.ai/stable/v#{version}/codeflow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d0b97198339bee6eadd224ba752575ed70ca57baf7d4fce796952fe6cb86c5df"
      url "https://pkg.productmind.ai/stable/v#{version}/codeflow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "codeflow"
  desc "Parallel AI coding agents and autonomous coding sessions"
  homepage "https://productmind.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codeflow"
  binary "cf-shell"
  binary "cf-attach"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/codeflow"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cf-shell"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cf-attach"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `codeflow init` for first-run setup, then `codeflow doctor` to verify
    your environment.

    Docker is required and is not installed by this cask.

    Public builds ship without a bundled TLS certificate for local previews.
    Set CODEFLOW_PREVIEW_TLS_CERT and CODEFLOW_PREVIEW_TLS_KEY to serve local
    previews over HTTPS; otherwise they are served over plain HTTP.
  EOS
end
