# This file was generated by GoReleaser. DO NOT EDIT.
cask "codeflow@beta" do
  version "0.1.0-alpha.454"

  on_macos do
    on_intel do
      sha256 "147d21cb1255622cba14ae87737f0100d18816ecdfeb52c967166314feb2c844"
      url "https://pkg.productmind.ai/beta/v#{version}/codeflow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0b4c0a295edab7239faedef51b4bd26fcf0520d34f927aafdf039bbc8bba61b6"
      url "https://pkg.productmind.ai/beta/v#{version}/codeflow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "05714c440aa9081bb2ae3baac602f6dccccc7ed7d7bc186b9b48912ef99fa06e"
      url "https://pkg.productmind.ai/beta/v#{version}/codeflow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "623093ea9bddbe09e59aa74a92637d5c5a250d04eacda98f2d10c5a654b4cf40"
      url "https://pkg.productmind.ai/beta/v#{version}/codeflow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "codeflow@beta"
  desc "Parallel AI coding agents and autonomous coding sessions"
  homepage "https://productmind.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codeflow"
  binary "cf-shell"
  binary "cf-attach"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/codeflow"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cf-shell"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cf-attach"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `codeflow init` for first-run setup, then `codeflow doctor` to verify
    your environment.

    Docker is required and is not installed by this cask.

    Public builds ship without a bundled TLS certificate for local previews.
    Set CODEFLOW_PREVIEW_TLS_CERT and CODEFLOW_PREVIEW_TLS_KEY to serve local
    previews over HTTPS; otherwise they are served over plain HTTP.
  EOS
end
