# This file was generated by GoReleaser. DO NOT EDIT.
cask "deslop-hook" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "9a7bd57a6151598e7d6b695c2122edfc084391cdab46226b92ecb08ac94d0b56"
      url "https://github.com/productmind-code/deslop-hook/releases/download/v#{version}/deslop-hook_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "28fbdbee59f33f23397acb7f62afe9ff829b416af152d68a5ab3a529884aa385"
      url "https://github.com/productmind-code/deslop-hook/releases/download/v#{version}/deslop-hook_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "22e98227d0fb64f4c180dd96a09e8bbbf4c300b5ff76c9b986df28ca12db5c3e"
      url "https://github.com/productmind-code/deslop-hook/releases/download/v#{version}/deslop-hook_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c05f56126a0f67311fff19f9d1e2b5625821fc88c57949b65d96a8deca9ca268"
      url "https://github.com/productmind-code/deslop-hook/releases/download/v#{version}/deslop-hook_#{version}_linux_amd64.tar.gz"
    end
  end

  name "deslop-hook"
  desc "Git pre-commit hook that removes AI-slop Unicode from staged changes"
  homepage "https://github.com/productmind-code/deslop-hook"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "deslop-hook"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/deslop-hook"]
    end
  end

  # No zap stanza required
end
