# This file was generated by GoReleaser. DO NOT EDIT.
cask "productmind@beta" do
  binary "codeflow", target: "pm"

  version "0.1.0-alpha.622"

  on_macos do
    on_intel do
      sha256 "dcaac91ab14ba2ce1e954524459ec9f425afe34d0cf9e9959f2b5c6e82608eb8"
      url "https://pkg.productmind.ai/beta/v#{version}/codeflow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "76d1962d308de657bfcf260c26805fcc97f01d4e09c634ec78f115b1731eefd7"
      url "https://pkg.productmind.ai/beta/v#{version}/codeflow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4359081a7472ce321145431dc42ff13659e556069c3d61981a0dcf8c6e03cbd2"
      url "https://pkg.productmind.ai/beta/v#{version}/codeflow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3a890e1ed2923769a44665bff343f02b7bc52f55adceffa86c7584e915b045e2"
      url "https://pkg.productmind.ai/beta/v#{version}/codeflow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "productmind@beta"
  desc "Productmind CLI (pm) — parallel AI coding agents and autonomous coding sessions"
  homepage "https://productmind.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codeflow"
  binary "cf-shell"
  binary "cf-attach"

  postflight do
    if File.exist?("/usr/bin/xattr")
      system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{staged_path}/codeflow"
      system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{staged_path}/cf-shell"
      system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{staged_path}/cf-attach"
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `pm init` for first-run setup, then `pm doctor` to verify your
    environment. (`codeflow` still works for now, but is deprecated.)

    Docker is required and is not installed by this cask.

    Public builds ship without a bundled TLS certificate for local previews.
    Set CODEFLOW_PREVIEW_TLS_CERT and CODEFLOW_PREVIEW_TLS_KEY to serve local
    previews over HTTPS; otherwise they are served over plain HTTP.
  EOS
end
