# This file was generated by GoReleaser. DO NOT EDIT.
cask "productmind" do
  binary "codeflow", target: "pm"

  version "0.0.1-739"

  on_macos do
    on_intel do
      sha256 "873be44b9b636bb3789c061aa25c429d368c49890271621e210c01deed826584"
      url "https://pkg.productmind.ai/stable/v#{version}/codeflow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f824ddbaeb06a3dcf3a448b19c36080789f3d2677081239163fb79c7c43fda3b"
      url "https://pkg.productmind.ai/stable/v#{version}/codeflow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ab063c512ade058343022d6bd0745cac7fe78b8f6021e931a7f7489c535afdf6"
      url "https://pkg.productmind.ai/stable/v#{version}/codeflow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3b3e0ccc9d90df799e4b8014e5ce3c36569b773bdb6b63100e0564515da8a484"
      url "https://pkg.productmind.ai/stable/v#{version}/codeflow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "productmind"
  desc "Productmind CLI (pm) - parallel AI coding agents and autonomous coding sessions"
  homepage "https://productmind.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codeflow"
  binary "cf-shell"
  binary "cf-attach"

  postflight do
    if File.exist?("/usr/bin/xattr")
      system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{staged_path}/codeflow"
      system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{staged_path}/cf-shell"
      system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{staged_path}/cf-attach"
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `pm init` for first-run setup, then `pm doctor` to verify your
    environment. (`codeflow` still works for now, but is deprecated.)

    Docker is required and is not installed by this cask.

    Public builds ship without a bundled TLS certificate for local previews.
    Set CODEFLOW_PREVIEW_TLS_CERT and CODEFLOW_PREVIEW_TLS_KEY to serve local
    previews over HTTPS; otherwise they are served over plain HTTP.
  EOS
end
