# This file was generated by GoReleaser. DO NOT EDIT.
cask "productmind" do
  binary "codeflow", target: "pm"

  version "0.0.1-744"

  on_macos do
    on_intel do
      sha256 "4176497ea3b0b1be57fe3382c79c623033fd71919fabf9bd711f757294d73c84"
      url "https://pkg.productmind.ai/stable/v#{version}/codeflow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "53b24141adc2a7bec135168f49a81c3a3da874c2737bc072c2fa24188d78503c"
      url "https://pkg.productmind.ai/stable/v#{version}/codeflow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0ec5071a916ab0c53e5b6571d9a5e41bf58240e12e4e1ee7bd88bdac840eff36"
      url "https://pkg.productmind.ai/stable/v#{version}/codeflow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5f64c88b3094f33a99e8ed7ad9c01af446f80684857a72b2f6bd40fb2bbac69c"
      url "https://pkg.productmind.ai/stable/v#{version}/codeflow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "productmind"
  desc "Productmind CLI (pm) - parallel AI coding agents and autonomous coding sessions"
  homepage "https://productmind.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codeflow"
  binary "cf-shell"
  binary "cf-attach"

  postflight do
    if File.exist?("/usr/bin/xattr")
      system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{staged_path}/codeflow"
      system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{staged_path}/cf-shell"
      system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{staged_path}/cf-attach"
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `pm init` for first-run setup, then `pm doctor` to verify your
    environment. (`codeflow` still works for now, but is deprecated.)

    Docker is required and is not installed by this cask.

    Public builds ship without a bundled TLS certificate for local previews.
    Set CODEFLOW_PREVIEW_TLS_CERT and CODEFLOW_PREVIEW_TLS_KEY to serve local
    previews over HTTPS; otherwise they are served over plain HTTP.
  EOS
end
