# This file was generated by GoReleaser. DO NOT EDIT.
cask "productmind@beta" do
  binary "codeflow", target: "pm"

  version "0.1.0-alpha.708"

  on_macos do
    on_intel do
      sha256 "4ddc67ff3d30cea5a1dfc7cc8562d637d7a3f83b4931966be652ee672e29a0bb"
      url "https://pkg.productmind.ai/beta/v#{version}/codeflow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2b7a948547f3b9270e6c75d72253cb12c4f445d91ab5c74ddf137385fac8991b"
      url "https://pkg.productmind.ai/beta/v#{version}/codeflow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "68a7b00b379151c5062835c539ce4ae1fafb50ee95bd19737f0dbc8825bece7f"
      url "https://pkg.productmind.ai/beta/v#{version}/codeflow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3080fb6fab239a9e35ace0cf9493853d03f313d370b37b0f6f8182d7c4a992e7"
      url "https://pkg.productmind.ai/beta/v#{version}/codeflow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "productmind@beta"
  desc "Productmind CLI (pm) - parallel AI coding agents and autonomous coding sessions"
  homepage "https://productmind.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codeflow"
  binary "cf-shell"
  binary "cf-attach"

  postflight do
    if File.exist?("/usr/bin/xattr")
      system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{staged_path}/codeflow"
      system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{staged_path}/cf-shell"
      system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{staged_path}/cf-attach"
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `pm init` for first-run setup, then `pm doctor` to verify your
    environment. (`codeflow` still works for now, but is deprecated.)

    Docker is required and is not installed by this cask.

    Public builds ship without a bundled TLS certificate for local previews.
    Set CODEFLOW_PREVIEW_TLS_CERT and CODEFLOW_PREVIEW_TLS_KEY to serve local
    previews over HTTPS; otherwise they are served over plain HTTP.
  EOS
end
