# This file was generated by GoReleaser. DO NOT EDIT.
cask "productmind@beta" do
  binary "codeflow", target: "pm"

  version "0.1.0-alpha.552"

  on_macos do
    on_intel do
      sha256 "e65e4ce189633056ef61afe637511ce1e8243ffb00758ec08bb3d22fd6d42a4e"
      url "https://pkg.productmind.ai/beta/v#{version}/codeflow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "88888169dda51d65f69fe5387e383e6e2647304707bba5521204243b7e0b6917"
      url "https://pkg.productmind.ai/beta/v#{version}/codeflow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d07ee376fc791c1e0e44761447f99ea520d9f2ab71f0b3314393db889f8dd4d0"
      url "https://pkg.productmind.ai/beta/v#{version}/codeflow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f5c477c3818f4a1deb0841ff1d3776f7fe665f5c1487d186bdf370ae405aae9e"
      url "https://pkg.productmind.ai/beta/v#{version}/codeflow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "productmind@beta"
  desc "Productmind CLI (pm) — parallel AI coding agents and autonomous coding sessions"
  homepage "https://productmind.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codeflow"
  binary "cf-shell"
  binary "cf-attach"

  postflight do
    if File.exist?("/usr/bin/xattr")
      system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{staged_path}/codeflow"
      system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{staged_path}/cf-shell"
      system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{staged_path}/cf-attach"
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `pm init` for first-run setup, then `pm doctor` to verify your
    environment. (`codeflow` still works for now, but is deprecated.)

    Docker is required and is not installed by this cask.

    Public builds ship without a bundled TLS certificate for local previews.
    Set CODEFLOW_PREVIEW_TLS_CERT and CODEFLOW_PREVIEW_TLS_KEY to serve local
    previews over HTTPS; otherwise they are served over plain HTTP.
  EOS
end
